import Layout from '@/components/layout'
import { Accordion, Button, Col, Form, InputGroup, Row } from 'react-bootstrap'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { CopyButton } from '@/components/form'
import Seo from '@/components/seo'
import { useToast } from '@/components/toast'
import { getGetServerSideProps } from '@/api/ssrApollo'
import {
  CATEGORIES,
  getInitialState,
  getDefaultPathForOption,
  isPathDefaultValue,
  OPTIONS_BY_KEY,
  OS_PATH_OPTION_KEYS,
  SELECT_OPTIONS
} from './options-data'

export const getServerSideProps = getGetServerSideProps({ query: null })

const CONFIG_PATHS = {
  windows: '%APPDATA%\\Bitcoin\\bitcoin.conf',
  mac: '~/Library/Application Support/Bitcoin/bitcoin.conf',
  linux: '~/.bitcoin/bitcoin.conf'
}

const OS_OPTIONS = [
  { value: 'windows', label: 'Windows' },
  { value: 'mac', label: 'Mac OS' },
  { value: 'linux', label: 'Linux' }
]

// Readable in both light and dark mode (avoid text-muted which can be too low-contrast in light theme)
const secondaryTextStyle = { color: 'var(--bs-body-color)', opacity: 0.85 }

// Inline code: theme-aware, no pink; fits body text
const inlineCodeStyle = {
  fontFamily: 'var(--bs-font-monospace)',
  fontSize: '0.9em',
  color: 'var(--bs-body-color)',
  backgroundColor: 'var(--bs-secondary-bg)',
  padding: '0.15em 0.4em',
  borderRadius: '0.25rem'
}

function getConfigPathForOS (os) {
  return CONFIG_PATHS[os] ?? null
}

function detectOS () {
  if (typeof navigator === 'undefined') return null
  const ua = navigator.userAgent
  const platform = navigator.userAgentData?.platform ?? navigator.platform ?? ''
  if (/Win(dows|32|64|16)/i.test(ua) || /Windows/i.test(platform)) return 'windows'
  if (/Mac|iPhone|iPad/i.test(platform) || /Mac/i.test(ua)) return 'mac'
  if (/Linux|Android/i.test(ua) || /Linux/i.test(platform)) return 'linux'
  return null
}

/** Normalize value for comparison with default */
function norm (val, opt) {
  if (val === undefined || val === null || val === '') return ''
  if (opt.widget === 'switch') {
    if (val === true || val === 1 || val === '1') return '1'
    return '0'
  }
  if (opt.widget === 'multi_switch') {
    const s = String(val).trim()
    if (!s) return ''
    return s.split(',').map(x => x.trim()).filter(Boolean).sort().join(',')
  }
  if (opt.widget === 'number') {
    const n = Number(val)
    return isNaN(n) ? '' : String(n)
  }
  if (opt.widget === 'number_float_8') {
    const n = parseFloat(String(val))
    return isNaN(n) ? '' : String(n)
  }
  return String(val).trim()
}

/** True if current value differs from default (so we should include in conf) */
function differs (optionKey, value, opt) {
  const def = opt.default
  const v = norm(value, opt)
  const d = norm(opt.widget === 'switch' ? (def === '1' || def === 'true') : def, opt)
  if (v === d) return false
  if (v === '' && d === '') return false
  return true
}

/** Split multi-line/comma list and filter empty */
function splitMulti (text) {
  if (text == null || text === '') return []
  return String(text).split(/[\n,]/).map(s => s.trim()).filter(Boolean)
}

function buildConfig (opts, configPathForComment, effectiveOS = null) {
  const lines = []
  lines.push('# Generated by Stacker News Bitcoin config Generator')
  lines.push('# https://stacker.news/bitcoin-config-generator')
  lines.push('')
  lines.push('# This config should be placed in following path:')
  if (configPathForComment) {
    lines.push(`# ${configPathForComment}`)
  } else {
    lines.push('# Linux: ~/.bitcoin/bitcoin.conf')
    lines.push('# macOS: ~/Library/Application Support/Bitcoin/bitcoin.conf')
    lines.push('# Windows: %APPDATA%\\Bitcoin\\bitcoin.conf')
  }
  lines.push('')

  const push = (key, lineStr, comment) => {
    const opt = OPTIONS_BY_KEY[key]
    if (opt && comment !== false) lines.push(`# ${opt.label}`)
    lines.push(lineStr)
  }

  const emitOption = (key, opt, optWithDefault, val) => {
    if (opt.widget === 'multi_switch') {
      const items = (val && String(val).trim()) ? String(val).split(',').map(s => s.trim()).filter(Boolean) : []
      if (items.length > 0) {
        push(key, `${key}=${items[0]}`)
        for (let i = 1; i < items.length; i++) lines.push(`${key}=${items[i]}`)
      }
      return
    }
    if (opt.widget === 'switch') {
      const on = val === true || val === 1 || val === '1'
      push(key, `${key}=${on ? '1' : '0'}`)
      return
    }
    if (opt.widget === 'textarea') {
      let items = splitMulti(val)
      const defaultItems = splitMulti(opt.default)
      if (items.length === 0 && defaultItems.length === 0) return
      if (items.length === defaultItems.length && items.every((v, i) => v === defaultItems[i])) return
      // Bitcoin Core uses at most 8 addnode connections
      if (key === 'addnode' && items.length > 8) {
        lines.push('# Bitcoin Core uses at most 8 addnode connections.')
        items = items.slice(0, 8)
      }
      if (items.length > 0) {
        push(key, `${key}=${items[0]}`)
        for (let i = 1; i < items.length; i++) lines.push(`${key}=${items[i]}`)
      }
      return
    }
    if (opt.widget === 'number' || opt.widget === 'number_float_8') {
      const n = opt.widget === 'number' ? Number(val) : parseFloat(val)
      if (val !== '' && val != null && !isNaN(n)) {
        if (opt.widget === 'number_float_8' && n < 0) return
        // Bitcoin Core prune: only 0, 1, or ≥550 are valid; 2–549 are invalid (treat as manual)
        let emitVal = key === 'prune' && n > 1 && n < 550 ? 1 : val
        // Core enforces minimum 1 for timeout and peertimeout
        if ((key === 'timeout' || key === 'peertimeout') && n < 1) emitVal = 1
        // Core dbcrashratio is 0–1
        if (opt.widget === 'number_float_8' && opt.max != null && n > Number(opt.max)) emitVal = Number(opt.max)
        // Clamp to opt.min/opt.max so emitted config is valid (e.g. URL or preset out-of-range)
        let numEmit = opt.widget === 'number' ? Number(emitVal) : parseFloat(emitVal)
        if (!isNaN(numEmit)) {
          if (opt.min != null && numEmit < Number(opt.min)) numEmit = Number(opt.min)
          if (opt.max != null && numEmit > Number(opt.max)) numEmit = Number(opt.max)
          push(key, `${key}=${numEmit}`)
        }
      }
      return
    }
    if (val !== '' && val != null && String(val).trim() !== '') {
      push(key, `${key}=${val}`)
    }
  }

  let firstSection = true
  for (const cat of CATEGORIES) {
    const optionKeysWithChanges = []
    for (const key of cat.keys) {
      const opt = OPTIONS_BY_KEY[key]
      if (!opt) continue
      const pathDefault = OS_PATH_OPTION_KEYS.includes(key) && effectiveOS ? getDefaultPathForOption(key, effectiveOS) : null
      const effectiveDefault = pathDefault !== null ? pathDefault : opt.default
      const optWithDefault = effectiveDefault !== opt.default ? { ...opt, default: effectiveDefault } : opt
      // Treat any path-default value as matching current OS so we don't include them (avoids flash on load/OS change)
      // Treat empty select as option default so we don't include when "use default" is intended
      const rawVal = opts[key]
      const valueToCompare = pathDefault !== null && isPathDefaultValue(key, rawVal)
        ? pathDefault
        : (opt.widget === 'select' && (rawVal === '' || rawVal == null) && opt.default !== '' ? opt.default : rawVal)
      if (differs(key, valueToCompare, optWithDefault)) optionKeysWithChanges.push({ key, opt, optWithDefault })
    }
    if (optionKeysWithChanges.length === 0) continue

    if (!firstSection) lines.push('')
    firstSection = false
    lines.push(`# [${cat.title}]`)
    for (const { key, opt, optWithDefault } of optionKeysWithChanges) {
      // -test= only applies to regtest; omit and comment when chain is not regtest
      if (key === 'test' && opts[key] && String(opts[key]).trim() && opts.chain !== 'regtest') {
        lines.push('# -test= only applies to regtest; omitted for current chain.')
        continue
      }
      // acceptstalefeeestimates only applies to regtest; omit when chain is not regtest
      if (key === 'acceptstalefeeestimates' && (opts[key] === true || opts[key] === 1 || opts[key] === '1') && opts.chain !== 'regtest') {
        lines.push('# acceptstalefeeestimates only applies to regtest; omitted for current chain.')
        continue
      }
      emitOption(key, opt, optWithDefault, opts[key])
    }
  }

  if (!firstSection) {
    lines.push('')
    lines.push('# Network-specific sections')
    lines.push('# By default, the options above apply to every chain (main, test, testnet4, signet, regtest).')
    lines.push('# To restrict an option to one network, place it under the corresponding [section] below.')
    lines.push('# addnode, connect, port, bind, rpcport, rpcbind and wallet are mainnet-only unless')
    lines.push('# you repeat them under another section.')
    lines.push('')
    lines.push('# Mainnet')
    lines.push('[main]')
    lines.push('')
    lines.push('# Testnet3')
    lines.push('[test]')
    lines.push('')
    lines.push('# Testnet4')
    lines.push('[testnet4]')
    lines.push('')
    lines.push('# Signet')
    lines.push('[signet]')
    lines.push('')
    lines.push('# Regtest')
    lines.push('[regtest]')
    lines.push('')
  }

  return lines.join('\n')
}

function serializeOptsForUrl (opts, targetOS = null) {
  const o = {}
  Object.keys(opts).forEach(k => {
    const v = opts[k]
    if (v === DEFAULT_OPTIONS[k]) return
    if (k !== 'predefinedPreset' && (v === '' || v === null || v === undefined)) return
    o[k] = v
  })
  if (targetOS !== null && targetOS !== undefined && targetOS !== '') o.targetOS = targetOS
  return btoa(unescape(encodeURIComponent(JSON.stringify(o))))
}

function deserializeOptsFromUrl (hash) {
  if (!hash || !hash.startsWith('#')) return null
  try {
    const json = decodeURIComponent(escape(atob(hash.slice(1))))
    const o = JSON.parse(json)
    const targetOS = o.targetOS
    const { targetOS: _dropped, ...rest } = { ...getInitialState(), ...o }
    return { opts: rest, targetOS }
  } catch {
    return null
  }
}

const DEFAULT_OPTIONS = { ...getInitialState(), predefinedPreset: '' }

// Presets mirror node classes from Bitcoin Core Config Generator (jlopp.github.io/bitcoin-core-config-generator)
const PRESET_KEYS = ['', 'mining', 'ports', 'lowbandwidth', 'pruned', 'raspberrypi', 'tor', 'testnet', 'regtest', 'nonsync', 'lightningeclair']

const PRESETS = {
  '': { label: 'Defaults', opts: { ...DEFAULT_OPTIONS, predefinedPreset: '' } },
  mining: {
    label: 'Mining',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'mining',
      dbcache: 4000,
      maxorphantx: 1000,
      maxmempool: 1000,
      blockreconstructionextratxn: 1000,
      maxsigcachesize: 100,
      blockmaxweight: 4000000,
      peerbloomfilters: false
    }
  },
  ports: {
    label: 'Non-standard Ports',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'ports',
      port: 8333,
      rpcport: 8332
    }
  },
  lowbandwidth: {
    label: 'Low Bandwidth',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'lowbandwidth',
      blocksonly: true,
      maxconnections: 20,
      maxuploadtarget: 500
    }
  },
  pruned: {
    label: 'Low Disk Usage (Pruned)',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'pruned',
      prune: 550,
      dbcache: 2000,
      persistmempool: true
    }
  },
  raspberrypi: {
    label: 'Raspberry Pi',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'raspberrypi',
      prune: 550,
      dbcache: 100,
      maxorphantx: 10,
      maxmempool: 50,
      maxconnections: 40,
      maxuploadtarget: 5000
    }
  },
  tor: {
    label: 'Privacy (Tor)',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'tor',
      onlynet: 'onion',
      listenonion: true,
      listen: false,
      proxy: '127.0.0.1:9050',
      onion: '127.0.0.1:9050',
      dns: false,
      dnsseed: false,
      torcontrol: '127.0.0.1:9051'
    }
  },
  testnet: {
    label: 'Testnet',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'testnet',
      chain: 'testnet4',
      rpcport: 18332,
      dbcache: 1000,
      logips: true
    }
  },
  regtest: {
    label: 'Regtest',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'regtest',
      chain: 'regtest',
      rpcport: 18443,
      dbcache: 500,
      logips: true,
      logtimemicros: true
    }
  },
  nonsync: {
    label: 'Non-syncing',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'nonsync',
      listen: false,
      maxconnections: 0,
      networkactive: false
    }
  },
  lightningeclair: {
    label: 'Lightning (Eclair)',
    opts: {
      ...DEFAULT_OPTIONS,
      predefinedPreset: 'lightningeclair',
      txindex: true,
      server: true,
      zmqpubhashtx: 'tcp://127.0.0.1:29000',
      zmqpubrawblock: 'tcp://127.0.0.1:29000'
    }
  }
}

const FLOAT_STEP = 0.00000001

function OptionField ({ optionKey, opts, update, effectiveOS = null }) {
  const opt = OPTIONS_BY_KEY[optionKey]
  if (!opt) return null
  const val = opts[optionKey]
  const { label, description, widget } = opt

  const setVal = (v) => update(optionKey, v)

  if (widget === 'switch') {
    const checked = val === true || val === 1 || val === '1'
    const acceptStaleOnlyRegtest = optionKey === 'acceptstalefeeestimates' && checked && opts.chain !== 'regtest'
    const pruneTxindexConflict = optionKey === 'txindex' && checked && (Number(opts.prune) > 0 || opts.prune === true || opts.prune === '1')
    const listenListenonionConflict = (optionKey === 'listen' && !checked && (opts.listenonion === true || opts.listenonion === 1 || opts.listenonion === '1')) ||
      (optionKey === 'listenonion' && checked && !(opts.listen === true || opts.listen === 1 || opts.listen === '1'))
    const forcednsseedDnsseedConflict = (optionKey === 'forcednsseed' && checked && !(opts.dnsseed === true || opts.dnsseed === 1 || opts.dnsseed === '1')) ||
      (optionKey === 'dnsseed' && !checked && (opts.forcednsseed === true || opts.forcednsseed === 1 || opts.forcednsseed === '1'))
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Check
          type='switch'
          id={optionKey}
          label={label}
          checked={checked}
          onChange={e => setVal(e.target.checked)}
        />
        {description && <Form.Text className='small d-block text-break mt-1' style={secondaryTextStyle}>{description}</Form.Text>}
        {acceptStaleOnlyRegtest && (
          <Form.Text className='small d-block text-break mt-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            acceptstalefeeestimates only applies to regtest. Current chain is {opts.chain || 'main'}; this option will be omitted in the generated config.
          </Form.Text>
        )}
        {pruneTxindexConflict && (
          <Form.Text className='small d-block text-break mt-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            Prune mode is incompatible with txindex in Bitcoin Core.
          </Form.Text>
        )}
        {listenListenonionConflict && (
          <Form.Text className='small d-block text-break mt-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            Bitcoin Core errors: cannot set listen=0 with listenonion=1.
          </Form.Text>
        )}
        {forcednsseedDnsseedConflict && (
          <Form.Text className='small d-block text-break mt-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            Bitcoin Core errors: cannot set forcednsseed when dnsseed is false.
          </Form.Text>
        )}
      </Form.Group>
    )
  }

  if (widget === 'multi_switch') {
    const enabledSet = new Set((val && String(val)) ? String(val).split(',').map(s => s.trim()).filter(Boolean) : [])
    const options = opt.multiSwitchOptions || []
    const toggle = (value, checked) => {
      const next = new Set(enabledSet)
      if (checked) next.add(value)
      else next.delete(value)
      setVal([...next].sort().join(','))
    }
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Label className='font-monospace small'>{label}</Form.Label>
        {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
        {options.map((o, i) => (
          <Form.Check
            key={i}
            type='switch'
            id={`${optionKey}-${o.value}`}
            label={o.label}
            checked={enabledSet.has(o.value)}
            onChange={e => toggle(o.value, e.target.checked)}
          />
        ))}
      </Form.Group>
    )
  }

  if (widget === 'select') {
    const options = SELECT_OPTIONS[optionKey] || []
    const current = (val !== '' && val != null) ? val : opt.default
    const testOnlyRegtest = optionKey === 'test' && current && opts.chain !== 'regtest'
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Label className='font-monospace small'>{label}</Form.Label>
        {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
        {testOnlyRegtest && (
          <Form.Text className='small d-block text-break mb-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            -test= only applies to regtest. Current chain is {opts.chain || 'main'}; this option will be omitted in the generated config.
          </Form.Text>
        )}
        <Form.Select value={current} onChange={e => setVal(e.target.value)}>
          {options.map((o, i) => (
            <option key={i} value={o.value}>{o.label}</option>
          ))}
        </Form.Select>
      </Form.Group>
    )
  }

  if (widget === 'textarea') {
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Label className='font-monospace small'>{label}</Form.Label>
        {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
        <Form.Control
          as='textarea'
          rows={3}
          value={val ?? ''}
          onChange={e => setVal(e.target.value)}
          placeholder={optionKey}
          className='font-monospace small'
        />
      </Form.Group>
    )
  }

  if (widget === 'number') {
    const minVal = (opt.min != null && opt.min !== '') ? Number(opt.min) : 0
    const maxVal = (opt.max != null && opt.max !== '') ? Number(opt.max) : undefined
    const allowNegative = minVal < 0
    const displayVal = (() => {
      if (val === '' || (val === '-' && allowNegative)) return val
      if (typeof val === 'string') return val
      const n = typeof val === 'number' ? val : parseInt(val, 10)
      return Math.max(minVal, maxVal != null ? Math.min(maxVal, n) : n)
    })()
    const numericDisplay = displayVal === '' || displayVal === '-' ? (allowNegative ? minVal : 0) : Number(displayVal)
    const step = 1
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Label className='font-monospace small'>{label}</Form.Label>
        {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
        {optionKey === 'prune' && !isNaN(numericDisplay) && numericDisplay > 1 && numericDisplay < 550 && (
          <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>
            Values 2–549 are stored as 1 (manual pruning) in the generated config.
          </Form.Text>
        )}
        {optionKey === 'prune' && !isNaN(numericDisplay) && numericDisplay > 0 && (opts.txindex === true || opts.txindex === 1 || opts.txindex === '1') && (
          <Form.Text className='small d-block text-break mb-1' style={{ ...secondaryTextStyle, color: 'var(--bs-warning)' }}>
            Prune mode is incompatible with txindex in Bitcoin Core.
          </Form.Text>
        )}
        <InputGroup size='sm'>
          <Button
            variant='primary'
            onClick={() => {
              const next = displayVal === '' || displayVal === '-' ? minVal : Math.max(minVal, numericDisplay - step)
              setVal(maxVal != null ? Math.min(maxVal, next) : next)
            }}
          >
            −
          </Button>
          <Form.Control
            type='text'
            inputMode={allowNegative ? 'text' : 'numeric'}
            min={minVal}
            max={maxVal}
            value={displayVal}
            onChange={e => {
              const v = e.target.value
              if (!/^-?\d*$/.test(v)) return
              if (v === '' || (v === '-' && allowNegative)) { setVal(v); return }
              const n = parseInt(v, 10)
              if (!isNaN(n) && n >= minVal && (maxVal == null || n <= maxVal)) setVal(n)
              else setVal(v)
            }}
            onKeyDown={e => {
              if (e.key === 'ArrowUp') {
                e.preventDefault()
                const next = displayVal === '' || displayVal === '-' ? minVal : numericDisplay + step
                setVal(maxVal != null ? Math.min(maxVal, next) : next)
              } else if (e.key === 'ArrowDown') {
                e.preventDefault()
                const next = displayVal === '' || displayVal === '-' ? minVal : Math.max(minVal, numericDisplay - step)
                setVal(maxVal != null ? Math.min(maxVal, next) : next)
              }
            }}
            placeholder={optionKey}
            className='font-monospace small'
          />
          <Button
            variant='primary'
            onClick={() => {
              const next = displayVal === '' || displayVal === '-' ? minVal : numericDisplay + step
              setVal(maxVal != null ? Math.min(maxVal, next) : next)
            }}
          >
            +
          </Button>
        </InputGroup>
      </Form.Group>
    )
  }

  if (widget === 'number_float_8') {
    const maxFloat = (opt.max != null && opt.max !== '') ? Number(opt.max) : undefined
    const numVal = val === '' || val == null ? '' : (typeof val === 'number' ? val : parseFloat(val))
    const displayVal = (() => {
      if (val === '' || val === '.' || (typeof val === 'string' && /\.$/.test(val))) return val
      if (numVal === '' || isNaN(numVal)) return val
      let v = Math.max(0, numVal)
      if (maxFloat != null && !isNaN(maxFloat) && v > maxFloat) v = maxFloat
      return v
    })()
    const step = FLOAT_STEP
    const numForStep = displayVal === '' || displayVal === '.' || isNaN(parseFloat(displayVal)) ? 0 : parseFloat(displayVal)
    const clamp = (n) => {
      let x = Math.max(0, n)
      if (maxFloat != null && !isNaN(maxFloat) && x > maxFloat) x = maxFloat
      return x
    }
    return (
      <Form.Group className='mb-3' key={optionKey}>
        <Form.Label className='font-monospace small'>{label}</Form.Label>
        {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
        <InputGroup size='sm'>
          <Button
            variant='primary'
            onClick={() => {
              const next = clamp(numForStep - step)
              setVal(Number.isInteger(next) ? next : parseFloat(next.toFixed(8)))
            }}
          >
            −
          </Button>
          <Form.Control
            type='text'
            inputMode='decimal'
            min={0}
            max={maxFloat}
            step={step}
            value={displayVal}
            onChange={e => {
              const v = e.target.value
              if (!/^\d*\.?\d{0,8}$/.test(v)) return
              if (v === '') { setVal(''); return }
              if (v === '.' || /\.$/.test(v)) { setVal(v); return }
              const n = parseFloat(v)
              if (!isNaN(n) && n >= 0) setVal(clamp(n))
              else setVal(v)
            }}
            onKeyDown={e => {
              if (e.key === 'ArrowUp') {
                e.preventDefault()
                const next = clamp(numForStep + step)
                setVal(Number.isInteger(next) ? next : parseFloat(next.toFixed(8)))
              } else if (e.key === 'ArrowDown') {
                e.preventDefault()
                const next = clamp(numForStep - step)
                setVal(Number.isInteger(next) ? next : parseFloat(next.toFixed(8)))
              }
            }}
            placeholder={optionKey}
            className='font-monospace small'
          />
          <Button
            variant='primary'
            onClick={() => {
              const next = clamp(numForStep + step)
              setVal(Number.isInteger(next) ? next : parseFloat(next.toFixed(8)))
            }}
          >
            +
          </Button>
        </InputGroup>
      </Form.Group>
    )
  }

  const isPassword = widget === 'password'
  const pathPlaceholder = OS_PATH_OPTION_KEYS.includes(optionKey) && effectiveOS ? getDefaultPathForOption(optionKey, effectiveOS) : ''
  const placeholder = pathPlaceholder || optionKey
  return (
    <Form.Group className='mb-3' key={optionKey}>
      <Form.Label className='font-monospace small'>{label}</Form.Label>
      {description && <Form.Text className='small d-block text-break mb-1' style={secondaryTextStyle}>{description}</Form.Text>}
      <Form.Control
        type={isPassword ? 'password' : 'text'}
        value={val ?? ''}
        onChange={e => setVal(e.target.value)}
        placeholder={placeholder}
        className='font-monospace small'
      />
    </Form.Group>
  )
}

export default function BitcoinconfigGenerator () {
  const [opts, setOpts] = useState(DEFAULT_OPTIONS)
  const [detectedOS, setDetectedOS] = useState(null)
  const [selectedOS, setSelectedOS] = useState(null)
  const [shareUrl, setShareUrl] = useState('')
  const toaster = useToast()

  useEffect(() => {
    const os = detectOS()
    setDetectedOS(os)
    setSelectedOS(prev => prev ?? os ?? 'linux')
  }, [])

  const effectiveOS = selectedOS ?? detectedOS ?? 'linux'
  const pathForDisplay = getConfigPathForOS(selectedOS ?? detectedOS ?? 'linux')

  useEffect(() => {
    if (typeof window === 'undefined') return
    const loaded = deserializeOptsFromUrl(window.location.hash)
    if (loaded) {
      setOpts(loaded.opts)
      if (loaded.targetOS != null && loaded.targetOS !== '') setSelectedOS(loaded.targetOS)
    }
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const encoded = serializeOptsForUrl(opts, selectedOS)
    const url = encoded ? `${window.location.pathname}#${encoded}` : window.location.pathname
    setShareUrl(url)
  }, [opts, selectedOS])

  // When OS is known or changes, set path options (blocksdir, datadir, etc.) to the correct default for that OS
  useEffect(() => {
    if (!effectiveOS) return
    setOpts(prev => {
      let changed = false
      const next = { ...prev }
      for (const key of OS_PATH_OPTION_KEYS) {
        if (isPathDefaultValue(key, prev[key])) {
          const pathDefault = getDefaultPathForOption(key, effectiveOS)
          if (prev[key] !== pathDefault) {
            next[key] = pathDefault
            changed = true
          }
        }
      }
      return changed ? next : prev
    })
  }, [effectiveOS])

  const update = useCallback((key, value) => {
    setOpts(prev => ({
      ...prev,
      [key]: value,
      predefinedPreset: key === 'predefinedPreset' ? value : ''
    }))
  }, [])

  const applyPreset = useCallback((key) => {
    if (key === undefined || key === null || !PRESETS[key]) return
    const presetOpts = PRESETS[key].opts
    const next = { ...presetOpts }
    if (effectiveOS) {
      for (const k of OS_PATH_OPTION_KEYS) {
        if (next[k] === '' || isPathDefaultValue(k, next[k])) {
          next[k] = getDefaultPathForOption(k, effectiveOS)
        }
      }
    }
    setOpts(next)
  }, [effectiveOS])

  const config = useMemo(() => buildConfig(opts, pathForDisplay, effectiveOS), [opts, pathForDisplay, effectiveOS])

  const handleSave = useCallback(async () => {
    try {
      if ('showSaveFilePicker' in window) {
        const handle = await window.showSaveFilePicker({
          suggestedName: 'bitcoin.conf',
          types: [{ description: 'Bitcoin config', accept: { 'text/plain': ['.conf'] } }]
        })
        const writable = await handle.createWritable()
        await writable.write(config)
        await writable.close()
      } else {
        const blob = new Blob([config], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'bitcoin.conf'
        a.click()
        URL.revokeObjectURL(url)
      }
    } catch (err) {
      if (err.name !== 'AbortError') console.error('Save failed:', err)
    }
  }, [config])

  const handleCopyShareLink = useCallback(async () => {
    const fullUrl = typeof window !== 'undefined' ? `${window.location.origin}${shareUrl}` : shareUrl
    try {
      await navigator.clipboard.writeText(fullUrl)
      toaster.success('Link copied to clipboard')
    } catch (err) {
      toaster.danger('Failed to copy link')
    }
  }, [shareUrl, toaster])

  return (
    <Layout footer footerLinks>
      <Seo title='Bitcoin Config Generator' />
      <div className='w-100 py-4 px-2'>
        <h1 className='mb-2'>Bitcoin Config Generator</h1>
        <p className='mb-4' style={secondaryTextStyle}>
          Generate a <code style={inlineCodeStyle}>bitcoin.conf</code> from options below. Only options that differ from defaults are included in the config.
        </p>
        <div className='w-100 mb-4'>
          <Form.Group className='mb-2'>
            <Form.Label className='small' style={secondaryTextStyle}>Config file location for:</Form.Label>
            <Form.Select
              value={selectedOS ?? 'linux'}
              onChange={e => {
                const newOS = e.target.value
                setSelectedOS(newOS)
                setOpts(prev => {
                  let changed = false
                  const next = { ...prev }
                  for (const key of OS_PATH_OPTION_KEYS) {
                    if (isPathDefaultValue(key, prev[key])) {
                      const pathDefault = getDefaultPathForOption(key, newOS)
                      if (prev[key] !== pathDefault) {
                        next[key] = pathDefault
                        changed = true
                      }
                    }
                  }
                  return changed ? next : prev
                })
              }}
              size='sm'
              className='mb-2'
            >
              {OS_OPTIONS.map(o => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </Form.Select>
          </Form.Group>
          <Form.Label className='small' style={secondaryTextStyle}>Save to:</Form.Label>
          <InputGroup size='sm'>
            <Form.Control
              readOnly
              value={pathForDisplay}
              className='font-monospace small'
              style={{
                backgroundColor: 'var(--bs-body-bg)',
                color: 'var(--bs-body-color, #212529)',
                minHeight: '2.25rem',
                overflow: 'hidden',
                whiteSpace: 'nowrap',
                textOverflow: 'ellipsis'
              }}
            />
            <CopyButton value={pathForDisplay} size='sm' />
          </InputGroup>
        </div>

        <Row className='w-100 g-3 g-lg-4'>
          <Col xs={12} lg={6}>
            <Form className='mb-4 mb-lg-0'>
              <Form.Group className='mb-3'>
                <Form.Label>Load preset</Form.Label>
                <Form.Select
                  value={PRESET_KEYS.includes(opts.predefinedPreset) ? opts.predefinedPreset : ''}
                  onChange={e => {
                    const k = e.target.value
                    if (PRESET_KEYS.includes(k)) applyPreset(k)
                  }}
                >
                  {Object.entries(PRESETS).map(([k, v]) => (
                    <option key={k || 'custom'} value={k}>{v.label}</option>
                  ))}
                </Form.Select>
                <Form.Text style={secondaryTextStyle}>Start from a predefined config, then tweak as needed.</Form.Text>
              </Form.Group>

              <Accordion className='mb-3'>
                {CATEGORIES.map(cat => (
                  <Accordion.Item key={cat.id} eventKey={cat.id}>
                    <Accordion.Header>{cat.title}</Accordion.Header>
                    <Accordion.Body>
                      {cat.keys.map(key => (
                        <OptionField key={key} optionKey={key} opts={opts} update={update} effectiveOS={effectiveOS} />
                      ))}
                    </Accordion.Body>
                  </Accordion.Item>
                ))}
              </Accordion>
            </Form>
          </Col>
          <Col xs={12} lg={6}>
            <div className='position-sticky' style={{ top: '3rem' }}>
              <Form.Group className='mb-2'>
                <Form.Label style={secondaryTextStyle}>Generated bitcoin.conf</Form.Label>
                <div className='position-relative'>
                  <Form.Control
                    as='textarea'
                    rows={28}
                    readOnly
                    value={config}
                    className='font-monospace small'
                    style={{ resize: 'vertical', minHeight: '24rem', paddingTop: '1rem', backgroundColor: 'var(--bs-body-bg)', color: 'var(--bs-body-color, #212529)' }}
                  />
                </div>
                <div className='d-flex flex-wrap justify-content-end gap-2 mt-2'>
                  <Button variant='primary' onClick={handleCopyShareLink}>Copy link</Button>
                  <Button variant='primary' onClick={handleSave}>Save</Button>
                </div>
              </Form.Group>
            </div>
          </Col>
        </Row>
      </div>
    </Layout>
  )
}
