#!/usr/bin/env bash

# https://github.com/benthecarman/nostr-wallet-connect-lnd

LND_HOST="${STACKER_LND_HOST:-localhost}"
LND_PORT="${STACKER_LND_GRPC_PORT:-10010}"

RUST_LOG=info nostr-wallet-connect-lnd \
  --relay wss://relay.damus.io \
  --lnd-host $LND_HOST --lnd-port $LND_PORT \
  --macaroon-file docker/lnd/stacker/regtest/admin.macaroon --cert-file docker/lnd/stacker/tls.cert \
  --keys-file scripts/nwc-keys.json
