ALTER TYPE "WalletName" ADD VALUE IF NOT EXISTS 'SPARK';

ALTER TYPE "WalletProtocolName" ADD VALUE IF NOT EXISTS 'SPARK';

ALTER TYPE "WalletSendProtocolName" ADD VALUE IF NOT EXISTS 'SPARK';

ALTER TYPE "WalletRecvProtocolName" ADD VALUE IF NOT EXISTS 'SPARK';
